### ISSUE TITLE
Lack to add documentation references in the exercise instructions.

### ISSUE THREAD

**Issue by FelipeFama** [exercism/typescript#1098]
I don't know if I should say it, but I'd really like it if you could add a documentation reference to the exercise instructions.
![issue](https://user-images.githubusercontent.com/91050670/181401735-a412b946-72f7-4fac-bb5b-d2bf2ebaac59.png)

**Comment by SleeplessByte** [comment]
Hi @FelipeFama, can you give an example?

**Comment by FelipeFama** [comment]
Hi @SleeplessByte I would like some examples in the instructions part and some reference to the exercise in the documentation.

**Comment by SleeplessByte** [comment]
Examples of how the code is called?
Or examples of colour combinations?

**Comment by FelipeFama** [comment]
Sorry for the delay in responding, in the javascript part there are some code examples in the instructions part of the exercise and there is always some reference in the documentation.

**Comment by SleeplessByte** [comment]
This will be added when we have a syllabus.
