### ISSUE TITLE
Need to add global.d.ts?

### ISSUE THREAD

**Issue by bttf** [exercism/typescript#125]
There will be compilation errors for all test files with use of global variables `declare`, `it`, `xit`, etc...

Should we add a `global.d.ts` (described [here](https://basarat.gitbooks.io/typescript/docs/project/globals.html)) that specifies these globals, and add them to each of the exercises?

**Comment by masters3d** [comment]
I am not sure I follow.

**Comment by masters3d** [comment]
declare, it and xit are part Jest. Am I missing something? I am not a js/ts expert.

**Comment by bttf** [comment]
anyone using a text editor that uses TypeScript's language services (tsserver) will see errors when they open the test files.

this is because `declare`, `it`, and `xit` are not declared anywhere in the global namespace

**Comment by masters3d** [comment]
I use vs code which auto imports jest. 
Other code editors also have auto import plug ins. 

This is also coming to TS server I think. 
https://github.com/Microsoft/TypeScript/pull/19069

**Comment by masters3d** [comment]
Is that what you were thinking?

**Comment by BrianDGLS** [comment]
This is not a code editor issue nor is it related to the Typescript language server.

@bttf,  In order to resolve your issues you need to run `npm install` or `yarn install` in the relevant directory. This will install `@types/jest` and remedy the issue..
