### ISSUE TITLE
Consider Using VSTS for CI 

### ISSUE THREAD

**Issue by masters3d** [exercism/typescript#126]
https://docs.microsoft.com/en-us/vsts/build-release/actions/ci-build-github

VSTS, has linux, mac and windows servers and they now support YAML.

**Comment by thedevelopnik** [comment]
Is this something that we would ask Katrina about and want to keep in line with the larger org?

**Comment by masters3d** [comment]
not really, the service is free and we have permissions to add it.

**Comment by thedevelopnik** [comment]
What's the value add over the current TravisCI usage? The multiple steps part looks cool and similar to Circle2 or Gitlab.

**Comment by masters3d** [comment]
Mostly learning experience, I've used GitlabCI and CircleCI too. Perhaps speed? Travisci is pretty slow during the day for the open source projects.

**Comment by thedevelopnik** [comment]
Yeah that makes sense to me.
