### ISSUE TITLE
Exercise ordering requires a bit of a tweak

### ISSUE THREAD

**Issue by nywilken** [exercism/typescript#191]
While testing with the latest release of Configlet the following violations were identified. One of which was previously fixed.

```
-> The exercise 'rational-numbers' is marked as core and unlocked by another exercise. A core exercise should not be unlocked by another.
-> The exercise 'binary-search-tree' is being unlocked by a non-core exercise. Non-core exercises can only be unlocked by core exercises.
-> The exercise 'variable-length-quantity' is being unlocked by a non-core exercise. Non-core exercises can only be unlocked by core exercises.
```

Instead of opening a PR to fix the violations based off my assumptions, I am opening up this issue so that a maintainer of the track can best advise on the proper exercise ordering from this point forward.

## Testing Steps
1. Download the latest release of Configlet [here](https://github.com/exercism/configlet/releases/tag/v3.8.0)
1. Run `configlet lint <path-to-fsharp-track>`
1. Validate that there are no lint errors.

Thanks in advance for the help.

**Comment by masters3d** [comment]
I don’t have a preference on the order.
