### ISSUE TITLE
Wrong test case in exercise transpose ("test many lines")

### ISSUE THREAD

**Issue by shybyte** [exercism/typescript#199]
The test case "test many lines" in https://github.com/exercism/typescript/blob/master/exercises/transpose/transpose.test.ts doesn’t match the canonical test case in https://github.com/exercism/problem-specifications/blob/6dba022a2a238566dd91991fdce5211b47feae8f/exercises/transpose/canonical-data.json. 
Actually in the current version (https://github.com/exercism/problem-specifications/blob/master/exercises/transpose/canonical-data.json) this test is replaced with a new test "mixed line length"

Using the correct test data will also require a new example program.

See also https://github.com/exercism/ecmascript/pull/379
and https://github.com/exercism/ecmascript/pull/364
for a fixed similar problem in the ecmascript track.

**Comment by masters3d** [comment]
PR’s welcome. 

We unfortunately do not try to keep up with the canonical data. Most of our exercises do not conform to the canonical data, it’s too much work for little gain. 

Now we just maintain forks of the exercise. If somebody comes along and is motivated enough to update the exercise then we take the contribution. 

Hope that helps.

**Comment by peerreynders** [comment]
I think the real issue here is that the [JavaScript](https://github.com/exercism/javascript/tree/master/exercises/transpose/README.md) and [TypeScript](https://github.com/exercism/javascript/blob/master/exercises/transpose/README.md) `README` have essentially identical exercise descriptions yet the `expected` for the `test many lines` test case are different.
```diff
● Transpose › test many lines

    expect(received).toEqual(expected) // deep equality

    - Expected  - 14
    + Received  + 14

    @@ -35,21 +35,21 @@
        "ismdsehphnnosa",
        "ncuse ra-tau l",
        " et  tormsural",
        "dniuthwea'g t ",
        "iennwesnr hsts",
    -   "g,ycoitkrttet",
    -   "n,l rs'a anr",
    -   "ief 'dgcgdi",
    -   "taol  eoe,v",
    -   "yneisl,u;e",
    -   ",.sftol ",
    -   "     ervdt",
    -   "     ;ie o",
    -   "       f,r ",
    -   "       eem",
    -   "       .me",
    -   "          on",
    -   "          vd",
    -   "          e.",
    +   "g,ycoi tkrttet",
    +   "n ,l r s'a anr",
    +   "i  ef  'dgcgdi",
    +   "t  aol   eoe,v",
    +   "y  nei sl,u; e",
    +   ",  .sf to l   ",
    +   "     e rv d  t",
    +   "     ; ie    o",
    +   "       f, r   ",
    +   "       e  e  m",
    +   "       .  m  e",
    +   "          o  n",
    +   "          v  d",
    +   "          e  .",
        "          ,",
      ]
```

A simplified test case may illustrate what is happening:

```typescript
  it("jagged padding", () => {
    const source = [
      "11",
      "2",
      "3333",
      "444",
      "555555",
      "66666"
    ]

    const transposed = [
      "123456",
      "1 3456",
      "  3456",
      "  3 56",
      "    56",
      "    5"
    ]

    const expected = [
      "123456",
      "13456",
      "  3456",
      "  356",
      "    56",
      "    5"
    ]
    expect(
      Transpose.transpose(source)
    ).toEqual(transposed)
  })
```

`transposed` is the actual _transposed_ result while `expected` is the result that the [TypeScript reference implementation](https://github.com/exercism/typescript/blob/master/exercises/transpose/transpose.example.ts) generates. The TypeScript reference implementation fails to provide intermittent padding when necessary:

```typescript
class Transpose {
  public static transpose(lines: string[]): string[] {
    return lines.reduce((result: string[], line, lineNo) => {
      line.split("").map((value, key) => {
        if (typeof result[key] === "undefined") {
          result[key] = new Array(lineNo + 1).join(" ")
        }

        // DEFECT: failure to pad for preceeding
        // source lines to the left that are too
        // short (unless they are at the very beginning)
        result[key] += value

        // At this point result[key].length should be
        // always (lineNo + 1)
        // Failure to apply intermittent padding
        // will result in
        // result[key].length < (lineNo + 1)
      })

      return result
    }, [])
  }
}
```

A fixed version would look something like this

```typescript
class Transpose {
  public static transpose(lines: string[]): string[] {
    return lines.reduce((result: string[], line, lineNo) => {
      line.split("").forEach((value, key) => {
        result[key] = (
          key in result ?
            result[key].padEnd(lineNo) :
            ' '.repeat(lineNo)
        ) + value
      })

      return result
    }, [])
  }
}
```

This version would have an identical `expected` to the [JavaScript `many lines` test](https://github.com/exercism/javascript/blob/master/exercises/transpose/transpose.spec.js).

**Comment by SleeplessByte** [comment]
@peerreynders you're correct. Would you be so kind to open a PR to fix the reference implementation and/or align the test?

**Comment by peerreynders** [comment]
Do the [Pull Request Guidelines](https://github.com/exercism/docs/blob/master/contributing/pull-request-guidelines.md) cover the full spectrum of conformance requirements? If so I'll see what I can do.

**Comment by SleeplessByte** [comment]
Yes @peerreynders, thanks for checking. https://github.com/exercism/typescript/blob/master/CONTRIBUTING.md is probably more helpful. 

In general:

- Make sure the title makes sense
- Put a short (or long explanation) in the body; in this case you can _link to your comment_ (it will suffice).
- Make sure the CI pass. If you can't get it to pass, feel free to ping me and I'll help ya out.

**Comment by peerreynders** [comment]
Repeating the obvious - see https://github.com/exercism/typescript/pull/371
