### ISSUE TITLE
Add instructions for debugging configuration

### ISSUE THREAD

**Issue by Alleno** [exercism/typescript#204]
Would it be possible for someone to add information about how to run a debug session in typescript? I've searched around on the VS Code documentation, and it doesn't seem to be well explained.

**Comment by CRivasGomez** [comment]
Hey @Alleno!
The easiest workaround would be to debug the transpiled JavaScript code.

**Comment by masters3d** [comment]
I know Visual Studio for windows has support for this. 

Visual Studio code has some support here https://code.visualstudio.com/Docs/languages/typescript#_javascript-source-map-support

We are not able to provide documentation for every editor out there ;( 

Reopen the issue if you are still having trouble.

**Comment by Alleno** [comment]
Hi Cheyo,

Thanks for your response. I am using VS Code, and I've seen those
instructions at the link but they seem kind of unclear. Maybe if I figure
it out I can make  PR to the instructions sheet.

All the best,

Allen
