### ISSUE TITLE
add version check to Package

### ISSUE THREAD

**Issue by masters3d** [exercism/typescript#207]
It would be nice if the version check was included in one of the script inside the package folder

"version-check": "tsc --version && jest --version && tslint --version"

also, we should probably move TSC, Jest to the dev dependencies.

**Comment by CRivasGomez** [comment]
>  would be nice if the version check was included in one of the script inside the package folder
> "version-check": "tsc --version && jest --version && tslint --version"

Why we need to check the version of tsc, jest and tslint if they are always the same for all users?

> also, we should probably move TSC, Jest to the dev dependencies.

Definitely yes 👍

**Comment by masters3d** [comment]
> Why we need to check the version of tsc, jest and tslint if they are always the same for all users?

Sanity check maybe? Do you know if the internal package is picked always over the global one if it exist?

**Comment by CRivasGomez** [comment]
> Do you know if the internal package is picked always over the global one if it exist?

Yes. As [the chapter `Modules` on Node.js documentation](https://nodejs.org/api/modules.html#modules_loading_from_node_modules_folders) states it in the [`Loading from node_modules Folders`](https://nodejs.org/api/modules.html#modules_loading_from_node_modules_folders) section:

> If the module identifier passed to require() is not a core module, and does not begin with '/', '../', or './', then Node.js starts at the parent directory of the current module, and adds /node_modules, and attempts to load the module from that location. Node will not append node_modules to a path already ending in node_modules.

**Comment by masters3d** [comment]
Sounds good.
