### ISSUE TITLE
Why jest --no-cache?

### ISSUE THREAD

**Issue by rootulp** [exercism/typescript#215]
`yarn test` currently runs `jest --no-cache` but the [docs](https://jestjs.io/docs/en/cli.html#cache) say
> Whether to use the cache. Defaults to true. Disable the cache using --no-cache. Note: the cache should only be disabled if you are experiencing caching related problems. On average, disabling the cache makes Jest at least two times slower.

So I'm wondering if `--no-cache` was set intentionally

**Comment by masters3d** [comment]
Yeah it was. The TS to JS traspiler to TS jest was having issues to we turned this on.
