### ISSUE TITLE
Perhaps exercise instructions could be made a little clearer?

### ISSUE THREAD

**Issue by sauntimo** [exercism/typescript#226]
### Background
I came to exercism because I wanted to learn typescript with practical problems, and you have lots and they're really interesting, which is great. I'm familiar with JS but I've just started a new job where they use typescript extensively so I need to get on it. 

### Problem?
So, I'm here to learn, but the scenarios themselves don't actually provide any guidance. Nothing about them so far (admittedly I'm only 5 in) seem to be specifically related to typescript, they're just interesting problems which could be solved in any number of languages. The prompts don't give any indication of how to solve the problem using typescript. That all has to be determined from the tests. So, I'm currently working on the Armstrong Numbers problem. I can quite happily write some code which will tell you if a number is an Armstrong Number. What I don't understand is whether I'm supposed to use a class, or an interface or whatever and I don't know how to determine what I'm supposed to do from the tests. Annoyingly, this is the kind of stuff that I really want to learn, the typescript specific stuff. The instruction is just `Write some code to determine whether a number is an Armstrong number.` which gives me nothing to go on, but the tests are in the form `expect(ArmstrongNumbers.isArmstrongNumber(5)).toBeTruthy()` and to me that looks like an object with a method, but I'm getting errors about types and properties which I don't understand.

I don't know if this is deliberate because in real life scenarios you don't always get much in the way of documentation etc, but given that I thought that this was a learning resource, it would be really useful if the prompt said something like "export a class with name `x` which has a function called `y` which returns a type `z`, which should implement an interface" or something. 

### Question
I guess I was wondering if the layout of the problems and their lack of guidance was by design, and what the thinking behind this was, or if actually people agreed that they would be improved by adding some pointers?

Or, have I misunderstood the purpose of the site? Is the idea that I go away somewhere else and learn how to write typescript on my own and then come back here to "prove" that I can do it by solving the exercises? that seems like it would be a bit of a waste as when I have learned what I need to, I'll carry on with my actual work rather than continuing to do tutorials and exercises. I guess I'm just not quite sure what the intended use of this site is, given it's lack of direction to learners.

### Apology
I'm sorry if this isn't the correct place for this comment - perhaps someone could point me in the right direction if there's a more appropriate forum.

**Comment by sauntimo** [comment]
So, I uploaded an mostly empty solution to see other peoples and it turns out that what I did wrong was not make my method a `static` method. I had never heard of static methods but I trotted off and read about them [in the docs](https://www.typescriptlang.org/docs/handbook/classes.html) and now I know about them and can happily use them. It just seems to me that the instructions could have said "You should implement a class `x` with a static method `y`. If you need further information about static methods in typescript, read the static methods section of [classes documentation](https://www.typescriptlang.org/docs/handbook/classes.html)" and this whole process would have been much smoother. I don't want to have to look at other people's solutions to figure out what I'm supposed to do - that takes all the fun away. I want to learn what tools there are and how to use them, and then figure how to apply them to the problems myself.

**Comment by masters3d** [comment]
Thanks for posting this issue. I am with you. We are open to accepting PR with changes to help drive this forward. Some of the other questions about the general design could probably be better answered at https://github.com/exercism/docs  Feel free to close this and/or open more narrowed scoped questions specific to TypeScript.

**Comment by sauntimo** [comment]
@masters3d thanks for getting back to me. I'll close this and try to find some time to put in PRs for some exercise specific improvements 😄
