### ISSUE TITLE
Error on "yargs" in test

### ISSUE THREAD

**Issue by JorisHey** [exercism/typescript#255]
Any idea how to fix next error output when running "yarn test"

```
yarn run v1.15.2
$ tsc --noEmit -p . && jest --no-cache
node_modules/@types/yargs/index.d.ts:212:106 - error TS2304: Cannot find name 'unknown'.

212         demand<K extends string>(key: K | ReadonlyArray<K>, msg?: string | true): Argv<T & { [key in K]: unknown }>;
                                                                                                             ~~~~~~~


node_modules/@types/yargs/index.d.ts:225:112 - error TS2304: Cannot find name 'unknown'.

225         demandOption<K extends string>(key: K | ReadonlyArray<K>, msg?: string | true): Argv<T & { [key in K]: unknown }>;
                                                                                                                   ~~~~~~~


node_modules/@types/yargs/index.d.ts:575:28 - error TS2304: Cannot find name 'unknown'.

575         [argName: string]: unknown;
                               ~~~~~~~


node_modules/@types/yargs/index.d.ts:733:9 - error TS2304: Cannot find name 'unknown'.

733         unknown;
            ~~~~~~~

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by SleeplessByte** [comment]
Hi there!

You most likely have installed `typescript` globally, and its version is most likely outdated.

Here is example output of running `yarn global list`:
```bash
yarn global list

info "typescript@3.2.2" has binaries:
   - tsc
   - tsserver
```

If this appears, and the version is lower than 3, this is definitely the issue. You can upgrade using:
```bash
yarn global upgrade typescript
```

The same issue can appear if your IDE comes with `typescript` bundled (like `vs code`). Upgrade your IDE in this case.

An alternative is to prepend the `tsc` command with `yarn`. It will then try to run it with the bundled `typescript` version inside the project folder's `npm_modules`:

```bash
yarn tsc --noEmit -p . && jest --no-cache
```

**Comment by JorisHey** [comment]
@SleeplessByte big thanks for your respons.
Unfortunately 
- I'm using typescript 3+
- I always have the latest version of VS code installed
- I have the same problem with "npm test" as "yarn test"

**Comment by SleeplessByte** [comment]
Hey again!

Have you tried manually running `yarn tsc --noEmit -p . && jest --no-cache`? So _not_ `yarn test` or `npm test`?

Also, is there a `tsconfig.json` in the tree (e.g. Your exercises might be at `C:/Exercism/typescript`, is there a `tsconfig.json` or `package.json` at C:/Exercism or C:/?)

**Comment by JorisHey** [comment]
Hello SleeplessByte

Yes... I've tried the yarn command (yarn tsc --noEmit -p . && jest --no-cache) with no positive result.
And both files are present. So there's a package.json file and a tsconfig.json

**Comment by SleeplessByte** [comment]
Just for my sanity, can you post the contents of package.json and tsconfig.json here? You can attach files by dragging and dropping them into the comment box.

**Comment by JorisHey** [comment]
[json.zip](https://github.com/exercism/typescript/files/3140913/json.zip)

**Comment by masters3d** [comment]
I don’t think we can help much here. This also remind me of Joe Armstrong video The mess we are in. https://youtu.be/lKXe3HUG2l4
