### ISSUE TITLE
Triangle exercise check invalid triangle when instantiated

### ISSUE THREAD

**Issue by lwaite2010** [exercism/typescript#264]
In the [Triangle exercise](https://github.com/exercism/typescript/tree/master/exercises/triangle), the tests check to see if the created triangle is valid when calling the `kind` function. However, I would argue that if you try to create a triangle with wrong sides, it should just fail instead of letting you continue on to testing the function.

It seems like it would be an easy fix, so is there a reason it is the way it is currently, or should I update the tests to work this way?

**Comment by masters3d** [comment]
We already throw in those cases? What sort of control flow you have in mind?

**Comment by SleeplessByte** [comment]
I think he means that it should throw in the constructor, not when calling `kind()`.

**Comment by lwaite2010** [comment]
@SleeplessByte That's what I meant, sorry it wasn't more clear.

So basically the tests would look like this:
```
it('triangles violating triangle inequality are illegal 2', () => {
    expect(() => {
        new Triangle(7, 3, 2);
    }).toThrow()
})
```
Instead of this:
```
it('triangles violating triangle inequality are illegal 2', () => {
    const triangle = new Triangle(7, 3, 2)
    expect(triangle.kind.bind(triangle)).toThrow()
})
```

**Comment by masters3d** [comment]
I think there’re are thow options

1) return a nullable object this way if the constructor can return null

2) extend the enum with one more value for ErrorTriangle or something along those lines.

**Comment by lwaite2010** [comment]
I’m not sure what you mean.

**Comment by masters3d** [comment]
```
it('triangles violating triangle inequality are illegal 2', () => {
    const triangle = new Triangle(7, 3, 2)
   expect(triangle).toBeNull();
})
```
or
```
it('triangles violating triangle inequality are illegal 2', () => {
    const triangle = new Triangle(7, 3, 2)
    expect(triangle.kind()).toEqual('ErrorTriangle')
})
```

I personal do not like throwing constructors because it forces all the callers to try catch

**Comment by lwaite2010** [comment]
@masters3d Sorry, I'm pretty new to TypeScript still. I've been looking to see how to return null from instantiating a class (for the first option you gave me), but I can't seem to find anything on how to do it.

The second option is what I'm trying to avoid (e.g., not knowing that the Triangle class doesn't work until you need it to). In an actual programming situation, I feel it would be better to have the code stop when the problem happens instead of later. So I'm trying to find a way to do that.

**Comment by masters3d** [comment]
I guess the first option is only avalible for static factories. https://github.com/Microsoft/TypeScript/issues/29893

**Comment by lwaite2010** [comment]
Alright. Since the current exercise setup is doing what it’s supposed to, and there doesn’t seem to be a simple way to change it without changing how the whole thing is done, I’ll just leave it the way it is.

Thanks for the informative discussion!

**Comment by SleeplessByte** [comment]
Return `null` from a constructor is almost as bad as throwing an error, albeit a bit less boilerplate. The latter indeed, as @masters3d says, forces _each caller_ to wrap in `try { } catch { }`, but the former forces _each caller_ to wrap in a null-check, which is similarly bad.

I completely understand what @lwaite2010 is asking for, and _why_ it is, but I think the pattern we're using in the exercise (late-throwing) is fine. If the triangle in this exercise was part of a real program, it could be that there are functions on it to _validate_ or _fix invalidities_, which would still work with the current pattern but not if validation was moved to the constructor.

My two cents, I agree with leaving as is.
