### ISSUE TITLE
Config Details

### ISSUE THREAD

**Issue by zgavin1** [exercism/typescript#28]
Would it be worth fleshing out the config.json file data? Currently every exercise is difficulty: 1 and have empty topics arrays.

I've been considering creating new exercises that would lend themselves to Typescript specific topics, like tsconfig options, typing with ```keyof``` and generic types, etc. Exercises like raindrops are good for picking up the basic syntax, but devs like myself could benefit from these. It would be easier for me to find an exercise like that if I could look for it in the topics.

Thoughts?

**Comment by masters3d** [comment]
Take a look at the F# track, they have detailed topics. I love generics. I also maintain the Swift track and we have some more advanced problems. The Rust track also has a really good story on progressive disclosure of problems difficulties that are specific to rust which could be emulated.
