### ISSUE TITLE
Pythagorean Triplet test cases producing 3 errors

### ISSUE THREAD

**Issue by vjba** [exercism/typescript#286]
Pythagorean Triplet exercise is producing 3 errors:
* "can make triplets up to 10"
* "can make triplets 11 through 20"
* "can filter on sum"

...all with the same error code `TS2339: Property 'sort' does not exist on type 'number'.
`

Console output from `$ yarn test`
```bash
yarn run v1.19.0
$ yarn lint:types && jest --no-cache
$ yarn tsc --noEmit -p .
pythagorean-triplet.test.ts:23:8 - error TS2339: Property 'sort' does not exist on type 'number'.

23       .sort()
          ~~~~

pythagorean-triplet.test.ts:31:8 - error TS2339: Property 'sort' does not exist on type 'number'.

31       .sort()
          ~~~~

pythagorean-triplet.test.ts:39:8 - error TS2339: Property 'sort' does not exist on type 'number'.

39       .sort()
          ~~~~


Found 3 errors.
```

For now I am just commenting out the cases. I'll look into the issue and attempt a solution for PR soon.

**Comment by SleeplessByte** [comment]
You have to return an array from the solution, not a single number.

**Comment by vjba** [comment]
Whoops. You're right. 

I should stop coding so late at night XD
