### ISSUE TITLE
Inconsistent versions of Eslint and typescript plugin

### ISSUE THREAD

**Issue by Cerberuser** [exercism/typescript#287]
I've just updated my previously completed exercises, according to the notification on the Exercism page, and suddenly run into a problem.

I'm using Visual Studio Code, and I've tried to make use of the TSLint plugin to catch linting errors on-the-fly. Now, as TSLint seems to be deprecated, I've migrated to ESLint, according to the new package.json (PR #276). But:
- On running `yarn`, it warned of incorrect peer dependency.
- In VSCode, it wasn't able to find the plugin.

It seems that providing eslint 6.x together with typescript-eslint 1.x doesn't make any sense. I've tried both eslint 5.x + typescript-eslint 1.x and eslint 6.x + typescript-eslint 2.x, and both combinations worked fine.

Shouldn't we fix this? If we should, that what pair is to be preferred?

**Comment by SleeplessByte** [comment]
Don't use tslint on this project.

**Comment by Cerberuser** [comment]
The question is about the `package.json` and `.eslintrc` included in the exercises. Are they correct, or is there really a inconsistency?

I admit, I've already worked with TS and now am looking for improvements, not for start. So, of course, I could remove `@typescript-eslint/eslint-plugin` from `.eslintrc` (together with all its rules) and remove `@typescript-eslint/eslint-plugin` from dependencies. But should I? And, more importantly, should the student do this, who is just starting?

Moreover, I've just checked it - even if I remove `@typescript-eslint/eslint-plugin`, I still have to retain `@typescript-eslint/parser` (otherwise eslint simply can't understand TypeScript syntax). And it has its version inconsistent with eslint, too:

> warning " > @typescript-eslint/parser@1.13.0" has incorrect peer dependency "eslint@^5.0.0".

Is that normal? If you think so, I'll follow, of course.

**Comment by SleeplessByte** [comment]
Just a heads up: you need to run `yarn install` _before_ opening the folder in vscode, _or_ reload vscode. The `eslint` plugin unfortunately most of the time does not initialise correctly when the `node_modules` dependencies are not present. This is an issue with the plugin, not with the `exercism` repo.

> But should I?

No, you should not remove this. 

> Is that normal? If you think so, I'll follow, of course.

Yes, but we'll update the dependencies soon, so this will go away 👍 👍 😄
