### ISSUE TITLE
[Readme Shared Code] Update name of sync configurations command and files synced

### ISSUE THREAD

**Issue by Roshanjossey** [exercism/typescript#295]
🐞 **Problem**
Information about the command to sync config files from `common` and the files that are synced are not up-to-date in [Shared Code](https://github.com/exercism/typescript#shared-code) section.

🎯 **Goal**
Have accurate information to help contributors.

💡 **Possible solutions**

Change 

`% make replacePackageFilesFromCommonToSubFolders`

to 

` % make sync-configurations`

and

```
 * package.json
 * tsconfig.json
 * tslint.json
 * yarn.lock
```

to 

```
 * .eslintignore
 * .eslintrc
 * jest.config.js 
 * package.json
 * tsconfig.json
 * yarn.lock
```

References: * [Relevant portion of Makefile](https://github.com/exercism/typescript/blob/master/Makefile#L114-L116), * [common directory](https://github.com/exercism/typescript/tree/master/common)

**Comment by mei4** [comment]
I just created [this PR](https://github.com/exercism/typescript/pull/328) to fix this issue.
