### ISSUE TITLE
Add stubs for files that doesn't have stubs.

### ISSUE THREAD

**Issue by Roshanjossey** [exercism/typescript#298]
Find the exercises that doesn't have stubs by going to https://tracks.exercism.io/typescript/master/stubs

🐞 **Problem**

From #278 

> The lack of stub file generates an unnecessary pain point within Exercism, contributing a significant proportion of support requests, making things more complex for our students, and hindering our ability to automatically run test-suites and provide automated analysis of solutions.
> 
> We believe that it’s essential to understand error messages, know how to use an IDE, and create files. However, getting this right as you’re just getting used to a language can be a frustrating distraction, as it can often require a lot of knowledge that tends to seep in over time. At the start, it can be challenging to google for all of these details: what file extension to use, what needs to be included, etc. Getting people up to speed with these things are not Exercism’s focus, and we’ve decided that we are better served by removing this source of confusion, letting people get on with actually solving the exercises.
> 
> The original discussion for this is at exercism/discussions#238.

🎯 **Goal**

Have stub files for all exercises to provide a better user experience.

💡 **Possible solutions**

We already have blank files of filename format `exercise-name.ts`
It needs to have what's expected by the test files. This needs to be added.
Look at the exercises that has stubs to understand what to add there.

**Comment by francismarcus** [comment]
Created a PR, will add some more commits during the weeknd
