### ISSUE TITLE
Recruiting additional maintainers for TypeScript

### ISSUE THREAD

**Issue by kytrinyx** [exercism/typescript#311]
We're about to start a big push towards version 3 (v3) of Exercism. This is going to be a really exciting step forward for Exercism, with in-browser coding, new Concept Exercises with automated feedback, improved mentoring and much more.

This to be a big community effort, with the work spread out among hundreds of volunteers across Exercism. One key thing is going to be each track having enough maintainers who have the time to manage that community effort. We are therefore putting out a call for new maintainers to bolster our numbers. We're hoping that our existing maintainers will be able to act as mentors to the newer maintainers we add, and take on a parental role in the tracks.

If you are an existing maintainer, could you please reply to this letting us know that you think you'll have time (2-3hrs/week) to help with this over the next 6 months. If you won't have that time, but still want to be a maintainer and just help where you can instead, please tell us that too. If you have come to the end of the road as a maintainer, then we totally understand that and appreciate all your effort, so just let us know.

For anyone new who's interested in becoming a maintainer, thanks for your interest! Being an Exercism maintainer is also a great opportunity to work with some other smart people, learn more about your language of choice, and gain useful skills and experience that are useful for growing your career in the technical leadership direction. Please write a comment below introducing yourself along with your Exercism handle, and telling us why you're interested in becoming a maintainer, and any relevant experience. We will then evaluate every application and contact you using your exercism email address once we have finished the evaluation process.

Thank you!

See also https://github.com/exercism/exercism/issues/5161

**Comment by msomji** [comment]
Hi my name is Maisam Somji ([msomji](https://exercism.io/profiles/msomji)) and I have been working on multiple different tracks in terms of practicing different exercises/learning new languages, mentoring others in completing their exercises as well as implementing new exercises for the tracks. With about 5 years of experience working with Javascript/Typescript/Java I have been a huge proponent of using exercism.io as a tool to help others learn different languages and hone in on their skills.
I would love to become a maintainer in these tracks in order to continue to help grow this platform so that it can impact others in the same way that is has impacted me!

**Comment by SleeplessByte** [comment]
Related: https://github.com/exercism/typescript/pull/310

I'll have time, just like on the JS track.

**Comment by darthbob88** [comment]
Hello, my name is Raymond Price. I've been mentoring on Exercism for a couple years, and been working in frontend web development for most of the past decade. If nothing else, this will probably be some nice resume polish.

**Comment by pmareke** [comment]
Hi @kytrinyx I would love to help in whatever you need.

Exericism is always my first choice when I have to learn a new language!

**Comment by joshiraez** [comment]
Hi, my name is Jose. I have been lurking Exercism for one year., first as a mentor, and although I put myself as a maintainer, I seldom have done many PR's until lately. 

I'm not sure if I'll be able to be a stable maintainer, but I'll stick around trying to help with the v3 remaining issues for launch, and who knows.

I have always wanted to jump into FOSS, and I liked Exercism and Camel. Sadly, it seemed all too daunting for me... until I saw the issues for v3, who seem low-apple enough for me to get started and up to speed, and well, here I am.

A pleasure to know you guys

**Comment by iHiD** [comment]
@joshiraez Thank you - excited to have your help 💙

**Comment by ErikSchierboom** [comment]
We're closing this issue as it was part of our push to implement the v3 version of this track and v3 has [just been released](https://exercism.org/blog/exercism-v3-has-launched).

New maintainer are always welcome though!
