### ISSUE TITLE
New Exercise ✨: DND Character

### ISSUE THREAD

**Issue by aes421** [exercism/typescript#344]
I'm going to work on implementing this exercise https://github.com/exercism/problem-specifications/blob/master/exercises/dnd-character/description.md

**Comment by SleeplessByte** [comment]
@aes421 did you end up doing the work? Are you stuck? Let me know!

**Comment by joshiraez** [comment]
If you can't do it or are stuck @aes421, I'm willing to pick this one up. Seems fun

**Comment by joshiraez** [comment]
I'll wait a few more days and I'll take it myself if there is no answer. Is that ok @SleeplessByte ?

**Comment by SleeplessByte** [comment]
You can take it now @joshiraez . Thanks for asking :)

**Comment by joshiraez** [comment]
I'll be doing this with the other one then as the first batch of exercises. Can you assign me to both? :)

**Comment by SleeplessByte** [comment]
Merged!
