### ISSUE TITLE
Add more exercises from ECMAScript to TypeScript

### ISSUE THREAD

**Issue by thedevelopnik** [exercism/typescript#37]
Below are exercises implemented in [the ES repo](https://github.com/exercism/xecmascript/tree/master/exercises) that could be easily translated to TS, that haven't already been implemented.

* Each new exercise should be submitted in its own PR that references this issue.
* Dependency versions should be consistent with the existing exercises.
* Exercise should be added to config.json
    * For now they can be added with a difficulty of 1, but a specific difficulty would be greatly appreciated.

The issue will be closed when all boxes are checked. 

* [x] acronym
* [ ] binary-search-tree
* [ ] clock
* [ ] largest-series-product
* [ ] linked-list
* [ ] nth-prime
* [ ] prime factors
* [ ] robot-simulator
* [ ] series
* [ ] sum-of-multiples

**Comment by masters3d** [comment]
I'd recommend to pick 10 or less for the list and then just open new issues for a new groping. It helps prioritize the work.

**Comment by dsudia** [comment]
@masters3d makes sense, I'll cut this down. Gonna start moving some over now. Sorry for the delay, we hit delivery of some major products in the last month.

**Comment by lilislilit** [comment]
Maybe...just maybe...It would be beneficial to separate them, or some other, with lower priority and assign hacktoberfest tag to those tasks? Preparations are in full swing in other tracks :)

**Comment by masters3d** [comment]
I am for separating them into individual issues.  Want to create them? I can add what ever tag they need. Let me know.

**Comment by lilislilit** [comment]
@masters3d Yeah, I will create them in a couple of hours.

**Comment by dsudia** [comment]
@lilislilit thanks for the help! I had been holding off to let all the config changes happen but now that those are going in this is a perfect time to jump in!

**Comment by lilislilit** [comment]
@dsudia It seems like I am not able to add labels tho.

**Comment by lilislilit** [comment]
https://github.com/exercism/csharp/issues/435 It should be added in lue of this, hope mainteners of this track will be able to do it soon for issues I created

**Comment by masters3d** [comment]
label added. Thanks @lilislilit !

**Comment by lilislilit** [comment]
Almost all of them are implemented. Are we sure we don't need to add another bunch while october is still going strong?

**Comment by masters3d** [comment]
@lilislilit Yes! go for it 👍

**Comment by lilislilit** [comment]
@masters3d Added a few more, hacktoberfest label for those would again be handy :)

**Comment by masters3d** [comment]
@lilislilit Thank you! This was a success! I am going to close this but I'll leave the remaining issues open.
