### ISSUE TITLE
Let the compiler shout at me on typeerrors:

### ISSUE THREAD

**Issue by NobbZ** [exercism/typescript#39]
I expect the following snippet to barf at me before even trying to execute the tests:

```ts
class HelloWorld {
    static hello(name = "World" : string): number {
        return "Hello, " + name + "!"
    }
}

export default HelloWorld
```

Instead of barfing, `yarn test && yarn lint` just complains about `string` beeing a variable name which clashes with a built in type:

```plain
yarn test v0.22.0
$ jest --no-cache
 PASS  ./hello-world.test.ts
  Hello World
    ✓ says hello world with no name (2ms)
    ✓ says hello to bob (1ms)
    ✓ says hello to sally

Test Suites: 1 passed, 1 total
Tests:       3 passed, 3 total
Snapshots:   0 total
Time:        1.063s
Ran all test suites.
Done in 1.79s.
yarn lint v0.22.0
$ tslint '*.ts?(x)'; exit 0

hello-world.ts[2, 35]: variable name clashes with keyword/type
Done in 0.48s.
```

So currently, in how the tests are run, it seems as if typescript is just another typeless hell around javascript. Therefore the request to do the following:

* Make the compiler fail on type errors (absolute minimum)
* Make the compiler (or the linter) warn or error (the former is totally enough I think) on missing types

**Comment by NobbZ** [comment]
PS: totally the same behaviour when s/string/number/

**Comment by NobbZ** [comment]
OK, in the meantime I was able to find out, that `tsc` will complain about a syntax error:

```plain
hello-world.ts(2,33): error TS1005: ',' expected.
```

After some googling I found that correct syntax for the class were:

```ts
class HelloWorld {
    static hello(name: number = "World"): number {
        return "Hello, " + name + "!"
    }
}
```

compiling this, now successfully complains about types beeing incorrect:

```plain
hello-world.ts(2,18): error TS2322: Type '"World"' is not assignable to type 'number'.
hello-world.ts(3,9): error TS2322: Type 'string' is not assignable to type 'number'.
hello-world.test.ts(11,29): error TS2345: Argument of type '"Bob"' is not assignable to parameter of type 'number'.
hello-world.test.ts(15,29): error TS2345: Argument of type '"Sally"' is not assignable to parameter of type 'number'.
```

Therefore I have to assume, that the typescript-track currently doesn't even use typescript!

**Comment by masters3d** [comment]
Good point. I filed a bug/feature question. 
As a work around we could run the compiler every time we run the tests to catch this
`    "test": "tsc -p . && jest --no-cache",
` 
I do think since ts-jest compiles the code before running jest that they should display any errors from the compiler and fail.

**Comment by NobbZ** [comment]
You filed a bug/feature where? Do you have a link/crossref?

**Comment by masters3d** [comment]
https://github.com/kulshekhar/ts-jest/issues/250

**Comment by NobbZ** [comment]
Also, a better way to alter the script line seems to be: `tsc --noEmit -p . && jest --no-cache`.

This way there is no javascript generated which leads to running the tests twice by `jest`

**Comment by masters3d** [comment]
What rabbit hole. Others are also using --noEmit. I think that is what we are going to use too: https://github.com/ds300/react-native-typescript-transformer/issues/13

**Comment by dsudia** [comment]
@masters3d 

Thanks for doing that PR! Looks like a good solution.
