### ISSUE TITLE
[v3] Add tags

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/typescript#396]
_This issue is part of the migration to v3. You can read full details about the various changes [here](https://github.com/exercism/v3-launch/)._

In Exercism v3, tracks can be annotated with tags. This allows searching for tracks with a certain tag combination, making it easy for students to find an interesting track to join.

Tags are specified in the top-level `"tags"` field in the track's `config.json` file and are defined as an array of strings, as specified in [the spec](https://github.com/exercism/v3-docs/blob/main/anatomy/tracks/config-json.md#tags).

## Goal

The `"tags"` field in the `config.json` file should be updated to contain the tags that are relevant to this track. The list of tags that can be used is listed in [the spec](https://github.com/exercism/v3-docs/blob/main/anatomy/tracks/config-json.md#tags).

## Example

```json
{
  "tags": [
    "runtime/jvm",
    "platform/windows",
    "platform/linux",
    "paradigm/declarative",
    "paradigm/functional",
    "paradigm/object_oriented"
  ]
}
```

## Tracking

https://github.com/exercism/v3-launch/issues/1

**Comment by joshiraez** [comment]
Can I take this? @SleeplessByte I was on the way to do it together with the key features

**Comment by SleeplessByte** [comment]
Yes. Can you create a TAGS.md document like we have in the JavaScript repo explaining why each tag was chosen/not chosen?

**Comment by joshiraez** [comment]
I'll take a look at the Javascript repo to see how its done and I'll try to imitate that :)

**Comment by joshiraez** [comment]
I have already submitted a PR with the changes, but I'm finding a lot of errors on the CI although I only touched 3 files. The prettier and linting things I have already fixed, but no idea why the tests and the version errors are all failing. Any ideas?

**Comment by SleeplessByte** [comment]
CI and configlet lint are failing on main right now, so you did great :)
