### ISSUE TITLE
Grade School Exercise - Map Implicitly Initialized Incorrectly

### ISSUE THREAD

**Issue by arcsector** [exercism/typescript#455]
## Problem Summary

The test for Exercise 10 (Grade School) implicitly defines all test Objects as `Map<string, string[]>` which is contrary to how it is initialized (this is from line 25):

```typescript
const expectedDb = new Map(Object.entries({ 2: ['Aimee'] }))
```

### Switch tests to correct explicit definition

Explicitly define `expectedDb` to be `Map<number, string[]>`:

```typescript
const expectedDb: Map<number, string[]> = new Map().set(2, ['Aimee']);
```

OR

```typescript
const expectedDb: Map<number, string[]> = new Map([ [2, ['Aimee']] ]);
```

The reasoning for this is that when you initialize using a generic `Map(Object.entries( {} ))`, but use a raw number type to insert in the dictionary `{ 2:  ['Aimee'] }`, this is confusing for the user, and doesn't provide the information that we should be using type `Map<string, string[]>`

### Switch tests to correct explicit initialization

Explicitly define `expectedDb` to be `Map<string, string[]>`:

```typescript
const expectedDb: Map<string, string[]> = new Map(Object.entries({ "2": ['Aimee'] }))
```

Note the two changes here are the explicit type definition as well as the stringify-ing of the number Map key.

**Comment by SleeplessByte** [comment]
Hi there!

5 hours ago I pushed an update to this exercise. Due to #387 it won't sync to the website just yet, but can you check if these tests and this proof of implementation would solve your issues?

https://github.com/exercism/typescript/blob/main/exercises/practice/grade-school/grade-school.test.ts

https://github.com/exercism/typescript/blob/main/exercises/practice/grade-school/.meta/proof.ci.ts

**Comment by arcsector** [comment]
@SleeplessByte Not particularly:

1. The method names are not the same as the previous version of the exercise
2. The test `roster cannot be modified outside of module` needs to have a result exception due to a possible undefined
3. The default datatype that everything is stored in is a plain dictionary as opposed to a Map

**Comment by SleeplessByte** [comment]
It's intentionally no longer a Map. You _can_ use a Map internally if you like, but the test suite doesn't impose it.

**Comment by arcsector** [comment]
Understood; I think persisting the current format of the datatypes as much as possible would be preferred to most users, especially those who have submitted public solutions, but other than that, yes this would satisfy this issue, since the default dictionary keys are type `number` and not implicitly interpreted as `string`.

I think we can close this if this is the way you're intending to go.

**Comment by SleeplessByte** [comment]
Eh. I'm in the middle. I totally see the value in persisting the data types as is. I do really like to keep these new methods names (because of the canonical dataset), but if you see a way to bring back `Map`, I'd take that PR!
