### ISSUE TITLE
Add windows CI

### ISSUE THREAD

**Issue by masters3d** [exercism/typescript#46]
HI @kytrinyx 

It looks like [csharp](https://ci.appveyor.com/project/kytrinyx/xcsharp/build/1.0.455) has support for windows boxes using appveyor under your name. 

We just had an issue #45 on windows on this track. Do you have a way to add typescript to the appveyor account so we can run windows tests?

Thanks!

**Comment by kytrinyx** [comment]
Yepp, I've turned on AppVeyor for this project. Let me know if you need me to tweak any settings or whatnot.

**Comment by masters3d** [comment]
yay got it working. Thanks!
