### ISSUE TITLE
Add stub exercise-name.ts files to each exercise

### ISSUE THREAD

**Issue by hoovercj** [exercism/typescript#57]
When a user first downloads a typescript exercise they have a directory with a test file that imports a ts file, but that ts file doesn't exist.

For example, 'hello-world.test.ts' imports './hello-world.ts' but there is no stub file.

It is an unnecessary step to require users to open the test file for every exercise to check which file they need to create.

**Comment by masters3d** [comment]
This is reasonable. We would also need to add a test to the CI to make sure all new exercises include a blank file.

**Comment by BrianDGLS** [comment]
I've added the stubs file and as well as a test for the CI in #65.

Ready for review.

**Comment by BrianDGLS** [comment]
@hoovercj @masters3d Happy for this issue to be closed?

**Comment by hoovercj** [comment]
I've only looked on my phone but it looks good. I really appreciate this, I think it adds the polish this track deserves. Thank you!

**Comment by masters3d** [comment]
@BrianDGLS Thanks for the PRs!
