### ISSUE TITLE
Incorrect formatting of package.json version in exercises

### ISSUE THREAD

**Issue by BrianDGLS** [exercism/typescript#63]
ISSUE:

When I fetch a new exercise running `npm install` fails due to an incorrectly formatted package.json number.

```npm WARN Invalid version: "0"```

FIX:

Add correctly formatted version number to the package.json files.

**Comment by masters3d** [comment]
Good catch. we need to add a CI pass for NPM. Currently we only test on Yarn.

**Comment by BrianDGLS** [comment]
@masters3d not sure how best to check this.

I've added `@cd $(INTDIR) && npm install && npm lintci && npm test` to the Makefile, this duplicates the yarn checks.

Is that enough?

**Comment by masters3d** [comment]
It should. That could be another PR too.

**Comment by BrianDGLS** [comment]
@masters3d I agree. I have removed the check as it was causing ci issues.

I think this should be a seperate pr, if it's needed. Validating the package.json doesnt seem to be straight forward, after playing round with it for a while.

There are a couple of npm packages which validate the package.json. They validate the entire file including author, license, etc.. So I think this would be best handled in a seperate Issue/PR.
