### ISSUE TITLE
implement largest-series-product

### ISSUE THREAD

**Issue by lilislilit** [exercism/typescript#70]
As per #37, port exercise from ecmascript track

**Comment by deyshin** [comment]
I'll work on this. 
Let's see how my evening goes.

**Comment by masters3d** [comment]
https://github.com/exercism/typescript/pull/94

**Comment by deyshin** [comment]
Setting up WSL to properly `make test` took a lot longer than I thought. I'm getting to it tomorrow finally. My apologies for the delay on such a simple task!

**Comment by deyshin** [comment]
Got it. I did not need to touch `make test` indeed. Thank you for the input! 
I submitted the [#108](https://github.com/exercism/typescript/pull/108). Please let me know if the PR needs any changes!

**Comment by deyshin** [comment]
I believe the issue is closed by the #108. Anything more to add?
