### ISSUE TITLE
Exercises using `test.skip()` have skipped tests marked as failed by analysis.

### ISSUE THREAD

**Issue by peerreynders** [exercism/typescript#759]
Examples:

https://exercism.org/tracks/typescript/exercises/palindrome-products/solutions/peerreynders
https://exercism.org/tracks/typescript/exercises/crypto-square/solutions/peerreynders

**Comment by SleeplessByte** [comment]
Should have been fixed by https://github.com/exercism/typescript-test-runner/pull/25

Can you resubmit these solutions and see if they now pass?

**Comment by peerreynders** [comment]
Just did crypto square:
- Submitted via CLI; result: failed
- Went to interactive mode; ran tests: passed; submitted: passed

```shell
crypto-square$ exercism version
exercism version 3.0.13
```

**Comment by SleeplessByte** [comment]
So it works on the web but not via the CLI? (Just want to confirm before I ask Erik and or jeremy to help me understand the difference between these two)

**Comment by peerreynders** [comment]
That was my experience (on Ubuntu 20.04 if that matters).
