### ISSUE TITLE
New Exercise ✨: Resistor Color Trio

### ISSUE THREAD

**Issue by rodmagaldi** [exercism/typescript#807]
Hello there! I'm new here, and I want to implement the following exercise:

https://github.com/exercism/problem-specifications/tree/main/exercises/resistor-color-trio

I saw resistor exercises on the typescript track, and I'm not happy with how the instructions are laid out for the students. I'd like to give it a go and see if I could do that any better.

Can anyone give me a green light for this?

Thanks a lot!

**Comment by SleeplessByte** [comment]
Closed by https://github.com/exercism/typescript/pull/814
