### ISSUE TITLE
RXJS

### ISSUE THREAD

**Issue by jorjun** [exercism/typescript#832]
Reactive programming (in typescript using the rxjs.js module) brings so much to the table vis typescript dev. and is such a novel way of working with the language that this module alone needs separate treatment... somehow.. the especial relevance is that typescript is so often used on the front end, and with GUI interaction rxjs really comes to the rescue by helping to keep on top of complexity. Isn't that the most optimal definition of what programming is all about (Donald Knuth said it first I believe).

Exercism already has comprehensive language tracks, we almost need concept tracks separated out. E.g. object orientation, functional, reactive, declarative, duck-typing,  etc.

**Comment by SleeplessByte** [comment]
> Exercism already has comprehensive language tracks, we almost need concept tracks separated out. E.g. object orientation, functional, reactive, declarative, duck-typing, etc.

Yes. This is one of the ideas we often discuss. 

cc @iHiD
