### ISSUE TITLE
Last unit test on 'Robot Name

### ISSUE THREAD

**Issue by mick-io** [exercism/typescript#857]
Whenever solutions are submitted, the server shows that the test are failing. I'm assuming this is due to a timeout. There is a comment above the last unit test that read "This test is optional." and it takes 15+ seconds to run.

**Comment by mick-io** [comment]
Whenever solutions are submitted, the server shows that the test are failing. I'm assuming this is due to a timeout. There is a comment above the last unit test that read "This test is optional." and it takes 15+ seconds to run.

**Comment by SleeplessByte** [comment]
Hi @mick-io , can you check if the tests in your solution have `xtest` or `test.skip`?

**Comment by mick-io** [comment]
None of the local test are being skipped and they're all passing. It just takes 16-19 seconds to run the entire suite. This is because the last test in the suite generates all possible names.
 
 ```typescript
 // This test is optional.
  it('all the names can be generated', () => {
    const usedNames = new Set()
    usedNames.add(robot.name)

    for (let i = 0; i < TOTAL_NUMBER_OF_NAMES - 1; i += 1) {
      const newRobot = new Robot()
      usedNames.add(newRobot.name)
    }

    expect(usedNames.size).toEqual(TOTAL_NUMBER_OF_NAMES)
  })
```

**Comment by SleeplessByte** [comment]
If the tests are not submitted, then the test _should_ have `test.skip`. If it's an older version of the excercise, it would be `xtest`.

The `test-runner` (https://github.com/exercism/typescript-test-runner) will automatically unskip _all_ tests that are `xtest`, but will keep `test.skip` alone, so to be able to skip optional tests like this one. It would then not time-out.

There could be a bug with that system, which is why I asked 😅 .

That said, if you want, we can optimise your solution so it runs in a second instead of 16?

**Comment by mick-io** [comment]
I'm quite curious what you would do to get that kind of performance  boost.

**Comment by SleeplessByte** [comment]
If you want, you can send me a private mentoring session request on Exercism, but I'm happy to give you some things to think about here:

- Is the execution in time linear? In other words: if you were to check only half the names, would that take half the time? Or more? Or less? Significantly less?
- What do you think is causing this big time difference?
- How many different names are there? Is that a big number or a small number? Is there something we can do with this information?

**Comment by joshuaswickirl** [comment]
I'm getting the same behavior. Submitting a solution with `xit('all the names can be generated', ...` does not resolve the issue.

The optional test is not optional nor is it communicated anywhere that the implementation should be linear.

![image](https://user-images.githubusercontent.com/31593215/150577767-20256654-8654-412b-ab82-0f304925e220.png)

```sh
 PASS  ./robot-name.test.ts (5.563 s)
  Robot
    ✓ has a name (2 ms)
    ✓ name is the same each time
    ✓ different robots have different names
    ✓ is able to reset the name (1 ms)
    ✓ should set a unique name after reset (6 ms)
    ✓ new names should not be sequential
    ✓ names from reset should not be sequential
    ✓ uses all letters
    ✓ uses all numbers (1 ms)
    ✓ all the names can be generated (5226 ms)

Test Suites: 1 passed, 1 total
Tests:       10 passed, 10 total
Snapshots:   0 total
Time:        5.756 s
Ran all test suites.
```

**Comment by SleeplessByte** [comment]
All `xit` tests are un _xitted_ (enabled). The test runner _should_ keep `it.skip`, but apparently it doesn't. 

The only quick workaround is to solve the exercise in O(n), but we will fix it properly. Just don't have the bandwidth to do that right now.

**Comment by SleeplessByte** [comment]
Has now been solved!
