### ISSUE TITLE
Why does two-bucket use both xtest and test.skip ?

### ISSUE THREAD

**Issue by glennj** [exercism/typescript#870]
https://github.com/exercism/typescript/blob/main/exercises/practice/two-bucket/two-bucket.test.ts

I have not checked any other exercises.

**Comment by SleeplessByte** [comment]
Because the _skipped_ tests were not green for the proof.ci solution. It was a way we could update the exercise without proving all the tests pass (see the JavaScript track for the same change). Either there or here, someone did solve it, but I guess didn't update the tests.
