### ISSUE TITLE
Ensure no exercise tests are skipped when running `make test`

### ISSUE THREAD

**Issue by BrianDGLS** [exercism/typescript#88]
Some exercise tests are skipped when running make test.

This happens as tests have been marked to be skipped using the `xtest` function.
Any occurrences of `xtest` should be replaced with `xit`.

**Comment by masters3d** [comment]
Good catch. We also need to find it.skip and xdescribe

**Comment by masters3d** [comment]
https://github.com/facebook/jest/blob/HEAD/packages/eslint-plugin-jest/docs/rules/no-disabled-tests.md

**Comment by BrianDGLS** [comment]
Added #89 for this.

Doesn't seem to be any occurrences of `it.skip` and `xdescribe`.
It looks like the usage of `xtest` comes from copying the ecmascript tests, so is something to keep an eye out for.

**Comment by masters3d** [comment]
cook. Let’s leave this open so we can update ci to catch this with a linter or similar.

**Comment by masters3d** [comment]
Also we should check if that all tests are ignored expect for the first one. https://github.com/exercism/typescript/pull/139
