### ISSUE TITLE
Two-Fer exercise skips 2/3 tests with `xit`

### ISSUE THREAD

**Issue by ZorgonPeterson** [exercism/typescript#939]
Hello!

I'm new to TypeScript, but during the `two-fer` exercise I noticed 2 tests were constantly being skipped:

```shell
$ yarn test
 PASS  ./two-fer.test.ts
  TwoFer
    ✓ no name given (2 ms)
    ○ skipped a name given
    ○ skipped another name given

Test Suites: 1 passed, 1 total
Tests:       2 skipped, 1 passed, 3 total
Snapshots:   0 total
Time:        1.558 s
Ran all test suites.
```

I got a bit curious and checked out the test when I noticed only the first test is using the `it` while the rest are using `xit`. When I changed the test(s) from `xit` to `it`, I was able to confirm the tests passed (and my submission worked in those cases )

```typescript
import { twoFer } from './two-fer'


describe('TwoFer', () => {

  it('no name given', () => {
    const expected = 'One for you, one for me.'
    expect(twoFer()).toEqual(expected)
  })

  it('a name given', () => {
    const expected = 'One for Alice, one for me.'
    expect(twoFer('Alice')).toEqual(expected)
  })

  it('another name given', () => {
    const expected = 'One for Bob, one for me.'
    expect(twoFer('Bob')).toEqual(expected)
  })
})
```

```shell
$ yarn test          
 PASS  ./two-fer.test.ts
  TwoFer
    ✓ no name given (1 ms)
    ✓ a name given
    ✓ another name given

Test Suites: 1 passed, 1 total
Tests:       3 passed, 3 total
Snapshots:   0 total
Time:        1.52 s
Ran all test suites.
```

Is this behavior intentional?

**Comment by glennj** [comment]
It's documented in the `HELP.md` file that comes with the exercise:

> ## Skipped tests
>
> In the test suites all tests but the first have been skipped.
>
> Once you get a test passing, you can enable the next one by changing `xit` to`it`.

**Comment by SleeplessByte** [comment]
Thanks @glennj for the swift answer <3
