### ISSUE TITLE
implement alphametics

### ISSUE THREAD

**Issue by lilislilit** [exercism/typescript#98]
As per #37, port exercise from ecmascript track

**Comment by delbertlegg** [comment]
I'll workn on this one.

**Comment by CRivasGomez** [comment]
Nice! 😀

**Comment by W0lfw00d** [comment]
I was also trying to fix this issue. 😰

I'm sure @delbertlegg's version will be better, but if someone could have a look at my pull request and tell me what's wrong with it. I would be grateful.

**Comment by masters3d** [comment]
Thanks for the PR. I think we need to add more October fest tags.

**Comment by delbertlegg** [comment]
@W0lfw00d No worries, go for it!
